packages:
  - "packages/*"
catalogs:
  spectrum-css:
    "@spectrum-css/actionbutton": ^7.1.3
    "@spectrum-css/alertbanner": ^3.1.1
    "@spectrum-css/button": ^14.1.6
    "@spectrum-css/card": ^11.1.0
    "@spectrum-css/divider": ^5.1.0
    "@spectrum-css/icon": ^9.1.0
    "@spectrum-css/link": ^7.1.0
    "@spectrum-css/menu": ^9.2.0
    "@spectrum-css/page": ^9.1.0
    "@spectrum-css/picker": ^9.1.4
    "@spectrum-css/sidenav": ^7.1.0
    "@spectrum-css/splitview": ^7.1.0
    "@spectrum-css/table": ^8.1.0
    "@spectrum-css/tokens": ^16.0.1
    "@spectrum-css/typography": ^8.1.0
